joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped  # ✅ must be interface_type for your version
      topic_name: bumperbot_controller/cmd_vel

      deadman_buttons: [5]  # RB

      axis_mappings:
        twist-linear-x: # Left stick vertical
          axis: 1
          scale: 1.0
          offset: 0.0

        twist-angular-z: # Right stick horizontal
          axis: 3
          scale: 1.0
          offset: 0.0  

